import type { ArticleSeed } from "./types"

// ロングテール SEO バッチ 1: 東京 × 建設業 9 職種 + 概論 = 10 記事
// 検索意図: 「東京 施工管理 求人」「東京 鳶 年収」など、地域 × 職種の長尾キーワード狙い
export const batch11: ArticleSeed[] = [
  {
    slug: "tokyo-management-jobs-guide",
    title: "東京で施工管理の求人を探す完全ガイド｜年収相場・大手ゼネコン・必要資格",
    excerpt:
      "東京の施工管理求人は全国最多。大手ゼネコン本社の集中、再開発案件の豊富さで、年収800万円以上のポストも珍しくありません。市場規模・年収・必要資格・キャリアパスまで実数ベースで解説します。",
    body: "&lt;p&gt;東京は &lt;strong&gt;施工管理職の求人数が全国で最も多い&lt;/strong&gt;エリアです。大手ゼネコン5社の本社がすべて東京にあり、丸の内・大手町・新宿・渋谷・品川の再開発案件が同時並行で動いているため、若手からベテランまで幅広いポジションがあります。本記事では、東京で施工管理として働く際に知っておきたい市場規模・年収・必要資格・キャリアパスを実数ベースで解説します。&lt;/p&gt;&lt;h2&gt;1. 東京の施工管理求人市場&lt;/h2&gt;&lt;p&gt;東京都内の建設投資額は &lt;strong&gt;年間11兆円&lt;/strong&gt;（2024年実績）で、全国シェアの約18%を占めます。大型再開発が集中するため、施工管理の有効求人倍率は &lt;strong&gt;6倍以上&lt;/strong&gt; と全職種で最も高い水準です。特に2025年以降、虎ノ門・赤坂・八重洲・池袋エリアの大規模プロジェクトが本格化しており、若手の採用枠が拡大しています。&lt;/p&gt;&lt;h2&gt;2. 年収相場（経験年数別）&lt;/h2&gt;&lt;table&gt;&lt;tr&gt;&lt;th&gt;経験年数&lt;/th&gt;&lt;th&gt;年収レンジ（東京）&lt;/th&gt;&lt;th&gt;主な役割&lt;/th&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;未経験〜3年&lt;/td&gt;&lt;td&gt;380〜480万円&lt;/td&gt;&lt;td&gt;施工管理補助、書類作成&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;3〜7年&lt;/td&gt;&lt;td&gt;500〜650万円&lt;/td&gt;&lt;td&gt;職長、安全・工程管理&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;7〜15年&lt;/td&gt;&lt;td&gt;650〜850万円&lt;/td&gt;&lt;td&gt;副所長、原価管理&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;15年以上&lt;/td&gt;&lt;td&gt;850〜1,200万円&lt;/td&gt;&lt;td&gt;所長、複数現場統括&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;p&gt;地方都市と比べて &lt;strong&gt;100〜200万円高い&lt;/strong&gt; のが東京の特徴です。都市手当・住宅手当が手厚い会社も多くあります。&lt;/p&gt;&lt;h2&gt;3. 必要な資格&lt;/h2&gt;&lt;ul&gt;&lt;li&gt;&lt;strong&gt;2級施工管理技士&lt;/strong&gt;: 入社1〜2年目で取得推奨。資格手当 月1〜2万円&lt;/li&gt;&lt;li&gt;&lt;strong&gt;1級施工管理技士&lt;/strong&gt;: 大規模現場の主任技術者になれる。資格手当 月3〜5万円&lt;/li&gt;&lt;li&gt;&lt;strong&gt;一級建築士&lt;/strong&gt;: 設計事務所兼務やゼネコン上層を目指すなら&lt;/li&gt;&lt;li&gt;&lt;strong&gt;監理技術者&lt;/strong&gt;: 1級＋実務経験5年以上で取得、公共工事の元請に必須&lt;/li&gt;&lt;/ul&gt;&lt;h2&gt;4. 求人が多い会社カテゴリ&lt;/h2&gt;&lt;p&gt;大手ゼネコン（鹿島・大林・清水・大成・竹中）、準大手（戸田・前田・五洋等）、中堅サブコン、施工管理派遣会社の4階層が共存しています。&lt;strong&gt;未経験中途は中堅サブコンか施工管理派遣&lt;/strong&gt;が現実的な入口で、3〜5年経験を積んでから準大手にステップアップする経路が王道です。&lt;/p&gt;&lt;h2&gt;5. 東京ならではのキャリアパス&lt;/h2&gt;&lt;p&gt;東京の現場は &lt;strong&gt;延床1万㎡超の超高層・複合用途案件&lt;/strong&gt; が多いため、地方では経験できないスケールの現場に若いうちから関われます。35歳までに大型物件の主任経験を積めば、40代で独立コンサルや海外案件への展開も視野に入ります。&lt;/p&gt;&lt;h2&gt;6. よくある質問&lt;/h2&gt;&lt;p&gt;&lt;strong&gt;Q. 残業はどのくらい？&lt;/strong&gt; A. 月45〜80時間が一般的。働き方改革で大手は月45時間以内に抑える方向。&lt;br&gt;&lt;strong&gt;Q. 土日休めますか？&lt;/strong&gt; A. 大手・準大手は4週8休が標準化。中堅以下は4週6休がまだ多い。&lt;br&gt;&lt;strong&gt;Q. 住宅手当は？&lt;/strong&gt; A. 月2〜5万円が相場。借上社宅制度を持つ会社も多い。&lt;/p&gt;&lt;h2&gt;まとめ&lt;/h2&gt;&lt;p&gt;東京の施工管理は &lt;strong&gt;案件規模・年収・キャリア&lt;/strong&gt;のすべてで全国トップクラス。未経験中途でも入口が広く、若手のうちに大型案件を経験できるのが最大の魅力です。&lt;/p&gt;",
    category: "job-type",
    subcategory: null,
    tags: ["東京", "施工管理", "年収", "求人"],
    metaDescription:
      "東京で施工管理の求人を探す方向け完全ガイド。市場規模、年収相場、必要資格、大手ゼネコンから派遣まで会社カテゴリ別の特徴、東京ならではのキャリアパスをゲンバキャリアが実数ベースで解説します。",
    publishedAt: new Date("2026-05-21T09:00:00+09:00"),
  },
  {
    slug: "tokyo-construction-jobs-guide",
    title: "東京で建築・躯体の求人を探す｜鳶・型枠・鉄筋・大工の年収と現場事情",
    excerpt:
      "東京の建築・躯体職人は再開発ラッシュで慢性的に不足。鳶・型枠・鉄筋・大工それぞれの東京での年収相場、求人傾向、独立までのキャリアパスを実例ベースで整理しました。",
    body: "&lt;p&gt;東京の建築・躯体職人は、超高層・大規模再開発の波で &lt;strong&gt;慢性的な人手不足&lt;/strong&gt; が続いています。職人不足の影響で日当が上昇傾向にあり、地方から出てきて稼ぐ20〜30代も多いエリアです。本記事では、鳶・型枠・鉄筋・大工の東京での働き方を実例ベースで解説します。&lt;/p&gt;&lt;h2&gt;1. 東京の躯体職人 需給状況&lt;/h2&gt;&lt;p&gt;東京都内の建築着工床面積は &lt;strong&gt;年間1,400万㎡&lt;/strong&gt;（2024年）。1棟あたり延床1万㎡超のRC・S造案件が常時20〜30現場稼働しており、躯体工事の職人需要は底堅く推移しています。日本鳶工業連合会の統計では、関東の鳶職人の充足率は &lt;strong&gt;75%前後&lt;/strong&gt; で慢性的な不足状態です。&lt;/p&gt;&lt;h2&gt;2. 職種別 日当・月収相場&lt;/h2&gt;&lt;table&gt;&lt;tr&gt;&lt;th&gt;職種&lt;/th&gt;&lt;th&gt;見習い日当&lt;/th&gt;&lt;th&gt;一人前日当&lt;/th&gt;&lt;th&gt;月収（稼働22日）&lt;/th&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;鳶&lt;/td&gt;&lt;td&gt;12,000〜15,000円&lt;/td&gt;&lt;td&gt;20,000〜28,000円&lt;/td&gt;&lt;td&gt;44〜62万円&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;型枠大工&lt;/td&gt;&lt;td&gt;11,000〜14,000円&lt;/td&gt;&lt;td&gt;19,000〜26,000円&lt;/td&gt;&lt;td&gt;42〜57万円&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;鉄筋工&lt;/td&gt;&lt;td&gt;11,000〜14,000円&lt;/td&gt;&lt;td&gt;18,000〜25,000円&lt;/td&gt;&lt;td&gt;40〜55万円&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;大工（造作）&lt;/td&gt;&lt;td&gt;12,000〜15,000円&lt;/td&gt;&lt;td&gt;20,000〜28,000円&lt;/td&gt;&lt;td&gt;44〜62万円&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;p&gt;東京は地方より &lt;strong&gt;日当が2,000〜3,000円高い&lt;/strong&gt; のが特徴。職長クラス（班長）になれば日当30,000円超、月収70万円も可能です。&lt;/p&gt;&lt;h2&gt;3. 求人が出やすい時期&lt;/h2&gt;&lt;p&gt;3〜5月の年度替わりと、9〜11月の下期スタート時に求人が増えます。大型現場の着工が集中する &lt;strong&gt;1月着工分（夏前完成）&lt;/strong&gt; に向けて、前年11〜12月に職人募集が出るパターンも多くあります。&lt;/p&gt;&lt;h2&gt;4. 入社前に取りたい資格&lt;/h2&gt;&lt;ul&gt;&lt;li&gt;&lt;strong&gt;玉掛け&lt;/strong&gt;（3日間講習・約3万円）&lt;/li&gt;&lt;li&gt;&lt;strong&gt;足場の組立て等作業主任者&lt;/strong&gt;（2日間講習・約2万円）&lt;/li&gt;&lt;li&gt;&lt;strong&gt;鉄筋施工技能士&lt;/strong&gt;（2級）または &lt;strong&gt;型枠施工技能士&lt;/strong&gt;（2級）&lt;/li&gt;&lt;li&gt;&lt;strong&gt;フォークリフト・小型移動式クレーン&lt;/strong&gt; 運転特別教育&lt;/li&gt;&lt;/ul&gt;&lt;h2&gt;5. 独立までの一般的ルート&lt;/h2&gt;&lt;p&gt;見習い2〜3年 → 一人前4〜5年 → 職長6〜10年 → 一人親方/会社設立 という流れが標準。東京は &lt;strong&gt;一人親方の単価が高く、独立で年収800〜1,200万円&lt;/strong&gt; を狙えます。ただし営業力・経理・労災保険など個人事業のリテラシーが必要で、独立前に1〜2年は副業や請負を経験しておくとリスクが下がります。&lt;/p&gt;&lt;h2&gt;6. 東京で働くデメリット&lt;/h2&gt;&lt;p&gt;通勤ラッシュ、物価・家賃の高さ、現場間移動の長さは覚悟が必要です。寮付き・現場直行直帰可の会社を選べば負担を軽減できます。&lt;/p&gt;&lt;h2&gt;まとめ&lt;/h2&gt;&lt;p&gt;東京は躯体職人にとって &lt;strong&gt;稼げる・成長できる・独立しやすい&lt;/strong&gt; トップエリア。資格を揃えて職長を目指せば、30代で年収700万円超は十分到達可能です。&lt;/p&gt;",
    category: "job-type",
    subcategory: null,
    tags: ["東京", "鳶", "型枠", "鉄筋", "大工", "年収"],
    metaDescription:
      "東京の建築・躯体職人（鳶・型枠・鉄筋・大工）の求人事情を解説。日当相場、月収目安、求人が出やすい時期、入社前資格、独立ルートまで、ゲンバキャリアが現場の実例ベースでまとめました。",
    publishedAt: new Date("2026-05-22T09:00:00+09:00"),
  },
  {
    slug: "tokyo-civil-jobs-guide",
    title: "東京の土木求人と年収相場｜首都圏インフラ更新時代の働き方",
    excerpt:
      "東京の土木業界は、老朽インフラ更新と再開発の二重需要で活況。土工・重機オペ・舗装の年収相場、公共工事と民間工事の違い、入社前資格、長期キャリア戦略を解説します。",
    body: "&lt;p&gt;東京の土木業界は、首都高や橋梁・上下水道などの &lt;strong&gt;老朽インフラ更新&lt;/strong&gt; と、再開発に伴う基盤整備の需要が重なり、長期的に求人が安定しています。本記事では東京で土木職として働く際の年収・職種別の働き方・キャリア戦略をまとめます。&lt;/p&gt;&lt;h2&gt;1. 東京の土木市場の特徴&lt;/h2&gt;&lt;p&gt;東京都の公共土木投資は &lt;strong&gt;年間6,000億円規模&lt;/strong&gt;。首都高更新（築地川区間・大師橋等）、東京外環自動車道、地下鉄延伸（有楽町線・南北線）、上下水道再構築など、10年単位の大型プロジェクトが進行中です。民間でも再開発地区の基盤造成・地下構造物工事の需要が安定しています。&lt;/p&gt;&lt;h2&gt;2. 職種別 年収レンジ&lt;/h2&gt;&lt;table&gt;&lt;tr&gt;&lt;th&gt;職種&lt;/th&gt;&lt;th&gt;未経験〜3年&lt;/th&gt;&lt;th&gt;5〜10年&lt;/th&gt;&lt;th&gt;15年以上&lt;/th&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;土工（一般作業員）&lt;/td&gt;&lt;td&gt;320〜400万円&lt;/td&gt;&lt;td&gt;420〜520万円&lt;/td&gt;&lt;td&gt;550〜650万円&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;重機オペレーター&lt;/td&gt;&lt;td&gt;380〜480万円&lt;/td&gt;&lt;td&gt;520〜650万円&lt;/td&gt;&lt;td&gt;680〜850万円&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;舗装工&lt;/td&gt;&lt;td&gt;350〜450万円&lt;/td&gt;&lt;td&gt;480〜600万円&lt;/td&gt;&lt;td&gt;600〜750万円&lt;/td&gt;&lt;td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;土木施工管理&lt;/td&gt;&lt;td&gt;400〜500万円&lt;/td&gt;&lt;td&gt;580〜750万円&lt;/td&gt;&lt;td&gt;800〜1,100万円&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;h2&gt;3. 公共工事と民間工事の違い&lt;/h2&gt;&lt;p&gt;東京都・国交省関東地整・首都高速など公共工事は &lt;strong&gt;週休2日・残業少なめ・賃金水準は安定&lt;/strong&gt;。民間（再開発基盤）は工程が厳しく残業多めですが、達成感と単価の振れ幅が大きいのが特徴です。&lt;/p&gt;&lt;h2&gt;4. 入社前に取りたい資格&lt;/h2&gt;&lt;ul&gt;&lt;li&gt;&lt;strong&gt;車両系建設機械運転技能講習&lt;/strong&gt;（バックホー、ホイールローダ等。3〜5日間・約5万円）&lt;/li&gt;&lt;li&gt;&lt;strong&gt;玉掛け＋小型移動式クレーン&lt;/strong&gt;（2点セットで現場の半分は対応可）&lt;/li&gt;&lt;li&gt;&lt;strong&gt;2級土木施工管理技士（補）&lt;/strong&gt;（学科のみで取得可、文系未経験でも可）&lt;/li&gt;&lt;li&gt;&lt;strong&gt;高所作業車運転技能講習&lt;/strong&gt;（橋梁・トンネル現場で重宝）&lt;/li&gt;&lt;/ul&gt;&lt;h2&gt;5. 求人が多いエリア・会社&lt;/h2&gt;&lt;p&gt;墨田・江東・葛飾・足立など下町エリアと、大田・品川など湾岸エリアに現場が集中。&lt;strong&gt;準大手ゼネコン土木部門&lt;/strong&gt;（戸田・西松・前田・大豊等）、地場の中堅土木会社、首都高関連の専門工事会社が主な採用元です。&lt;/p&gt;&lt;h2&gt;6. 長期キャリア戦略&lt;/h2&gt;&lt;p&gt;東京の土木は &lt;strong&gt;インフラ更新が今後20年続く&lt;/strong&gt; ことが確定的で、職を失うリスクが極めて低い分野です。1級土木施工管理技士＋技術士補を目指せば、50代以降も発注者支援・コンサル業務で活躍できます。&lt;/p&gt;&lt;h2&gt;まとめ&lt;/h2&gt;&lt;p&gt;東京の土木は派手さは無いものの &lt;strong&gt;安定性・年収・将来性&lt;/strong&gt; のバランスが優れた分野。重機ライセンスと2級土施を揃えれば30代で年収600万円が見えてきます。&lt;/p&gt;",
    category: "job-type",
    subcategory: null,
    tags: ["東京", "土木", "年収", "重機オペレーター", "インフラ"],
    metaDescription:
      "東京の土木求人を職種別の年収レンジ、公共工事と民間工事の違い、入社前資格、求人エリア、長期キャリア戦略まで解説。インフラ更新需要で安定する東京の土木業界の実態をゲンバキャリアがまとめます。",
    publishedAt: new Date("2026-05-23T09:00:00+09:00"),
  },
  {
    slug: "tokyo-electrical-jobs-guide",
    title: "東京の電気・設備工事士 求人と年収｜BEMS・再エネ時代の働き方",
    excerpt:
      "東京の電気・設備工事士は再開発と省エネ改修の二重需要で慢性的不足。電工・配管・空調職それぞれの東京での年収、第一種電工取得のメリット、独立可能性を解説します。",
    body: "&lt;p&gt;東京の電気・設備工事は、新築の再開発と既存ビルの &lt;strong&gt;省エネ改修（BEMS導入・LED化）&lt;/strong&gt; の二重需要で、職人不足が深刻化しています。本記事では、電工・配管・空調職の東京での働き方と年収を実例ベースで解説します。&lt;/p&gt;&lt;h2&gt;1. 東京の電気・設備市場&lt;/h2&gt;&lt;p&gt;東京の設備工事市場は &lt;strong&gt;年間2.5兆円&lt;/strong&gt;（一般社団法人日本電設工業協会推計）。大手電設会社5社（関電工・きんでん・かんでん・九電工・トーエネック）の関東支社、サブコン中堅、地場専門工事会社の3階層が共存しています。再開発の竣工ラッシュで、向こう5年は仕事が枯れることはありません。&lt;/p&gt;&lt;h2&gt;2. 職種別 年収相場&lt;/h2&gt;&lt;table&gt;&lt;tr&gt;&lt;th&gt;職種&lt;/th&gt;&lt;th&gt;未経験〜3年&lt;/th&gt;&lt;th&gt;5〜10年&lt;/th&gt;&lt;th&gt;15年以上&lt;/th&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;電気工（第二種電工）&lt;/td&gt;&lt;td&gt;350〜450万円&lt;/td&gt;&lt;td&gt;500〜650万円&lt;/td&gt;&lt;td&gt;700〜900万円&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;電気主任技術者（第三種）&lt;/td&gt;&lt;td&gt;420〜520万円&lt;/td&gt;&lt;td&gt;600〜800万円&lt;/td&gt;&lt;td&gt;900〜1,200万円&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;配管工&lt;/td&gt;&lt;td&gt;340〜440万円&lt;/td&gt;&lt;td&gt;480〜620万円&lt;/td&gt;&lt;td&gt;650〜850万円&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;空調設備施工&lt;/td&gt;&lt;td&gt;360〜460万円&lt;/td&gt;&lt;td&gt;500〜650万円&lt;/td&gt;&lt;td&gt;700〜900万円&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;h2&gt;3. 第一種電気工事士 取得のメリット&lt;/h2&gt;&lt;p&gt;第一種電工は &lt;strong&gt;500kW未満の自家用電気工作物まで施工可能&lt;/strong&gt;。商業ビル・工場の高圧受電盤まで触れるため、職場の選択肢と年収が一気に広がります。東京では第一種電工保有者の資格手当が &lt;strong&gt;月2〜4万円&lt;/strong&gt; の会社が多く、年収換算で30〜50万円アップ。受験費用は1万円程度、合格率は学科60%・技能65%です。&lt;/p&gt;&lt;h2&gt;4. 再エネ・BEMS 案件の増加&lt;/h2&gt;&lt;p&gt;東京では PPA（電力購入契約）方式の屋上太陽光や、ZEB（ゼロエネルギービル）化改修案件が急増。&lt;strong&gt;太陽光発電施工士&lt;/strong&gt;、&lt;strong&gt;高圧ガス製造保安責任者（冷凍機械）&lt;/strong&gt;などの周辺資格を持つと差別化できます。&lt;/p&gt;&lt;h2&gt;5. 一人親方として独立する道&lt;/h2&gt;&lt;p&gt;電気工事士は &lt;strong&gt;個人事業として独立しやすい&lt;/strong&gt; 職種の代表格。東京では建設業許可（電気工事業）を取って独立する人が多く、年収1,000万円超も珍しくありません。ただし顧客開拓と材料調達の手間が増えるため、独立前に2〜3年は元請会社との関係を作っておくのがコツです。&lt;/p&gt;&lt;h2&gt;6. よくある質問&lt;/h2&gt;&lt;p&gt;&lt;strong&gt;Q. 未経験でも入れる？&lt;/strong&gt; A. 30代までなら可。入社後すぐに第二種電工を取らせる会社が多い。&lt;br&gt;&lt;strong&gt;Q. 危険じゃない？&lt;/strong&gt; A. 感電・墜落のリスクはゼロではない。低圧電気取扱業務特別教育を必ず受講する。&lt;br&gt;&lt;strong&gt;Q. 体力は必要？&lt;/strong&gt; A. 配管・空調は重い管材を扱うため必要。電工は他職種よりは負担少なめ。&lt;/p&gt;&lt;h2&gt;まとめ&lt;/h2&gt;&lt;p&gt;東京の電気・設備は &lt;strong&gt;需要・年収・独立可能性&lt;/strong&gt; どれを取っても優れた分野。第一種電工＋専門資格を揃えれば、長期的に年収800万円以上を維持できます。&lt;/p&gt;",
    category: "job-type",
    subcategory: null,
    tags: ["東京", "電気工事士", "配管", "空調", "年収"],
    metaDescription:
      "東京の電気・設備工事士の求人事情を解説。電工・配管・空調別の年収相場、第一種電工取得のメリット、BEMS/再エネ案件の増加、独立への道までゲンバキャリアが実例ベースでまとめます。",
    publishedAt: new Date("2026-05-24T09:00:00+09:00"),
  },
  {
    slug: "tokyo-interior-jobs-guide",
    title: "東京の内装・仕上げ職人 求人と年収｜クロス・塗装・左官の働き方",
    excerpt:
      "東京の内装・仕上げ職人はオフィス改修と住宅リフォーム需要で活況。クロス・塗装・左官・タイルそれぞれの東京での年収、技能士資格、独立への道筋を実例ベースで紹介します。",
    body: "&lt;p&gt;東京の内装・仕上げ職人は、&lt;strong&gt;オフィス改修・店舗内装・マンションリフォーム&lt;/strong&gt; の3本柱で安定した需要があります。コロナ後のワークスタイル変化でオフィス改装が増え、富裕層向け高級リフォームも好調です。本記事では、クロス・塗装・左官・タイル工の東京での働き方をまとめます。&lt;/p&gt;&lt;h2&gt;1. 東京の内装市場の特徴&lt;/h2&gt;&lt;p&gt;東京の内装工事市場は &lt;strong&gt;年間1.5兆円&lt;/strong&gt; 規模。新築・改修比率がほぼ50:50で、改修案件が増加傾向にあります。1案件あたり工期1〜2週間の短期回転が多く、職人の腕次第で稼ぎが大きく変わります。&lt;/p&gt;&lt;h2&gt;2. 職種別 単価・年収相場&lt;/h2&gt;&lt;table&gt;&lt;tr&gt;&lt;th&gt;職種&lt;/th&gt;&lt;th&gt;日当（東京一人前）&lt;/th&gt;&lt;th&gt;月収目安&lt;/th&gt;&lt;th&gt;年収目安&lt;/th&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;クロス職人&lt;/td&gt;&lt;td&gt;18,000〜25,000円&lt;/td&gt;&lt;td&gt;40〜55万円&lt;/td&gt;&lt;td&gt;480〜660万円&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;塗装工&lt;/td&gt;&lt;td&gt;17,000〜23,000円&lt;/td&gt;&lt;td&gt;37〜51万円&lt;/td&gt;&lt;td&gt;450〜620万円&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;左官&lt;/td&gt;&lt;td&gt;18,000〜26,000円&lt;/td&gt;&lt;td&gt;40〜57万円&lt;/td&gt;&lt;td&gt;480〜690万円&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;タイル工&lt;/td&gt;&lt;td&gt;19,000〜27,000円&lt;/td&gt;&lt;td&gt;42〜60万円&lt;/td&gt;&lt;td&gt;500〜720万円&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;p&gt;一人親方として独立すれば、月収70万円以上も狙えます。腕の良い左官・タイル職人は東京で &lt;strong&gt;年収800〜1,000万円&lt;/strong&gt; に到達するケースもあります。&lt;/p&gt;&lt;h2&gt;3. 求人が多い案件タイプ&lt;/h2&gt;&lt;ul&gt;&lt;li&gt;オフィス入退去工事（夜間・短工期）&lt;/li&gt;&lt;li&gt;高級マンション内装（仕上げ精度重視）&lt;/li&gt;&lt;li&gt;商業店舗 リニューアル（飲食・アパレル）&lt;/li&gt;&lt;li&gt;戸建てリフォーム（個人施主直接受注も可能）&lt;/li&gt;&lt;/ul&gt;&lt;h2&gt;4. 取りたい技能士資格&lt;/h2&gt;&lt;p&gt;&lt;strong&gt;内装仕上げ施工技能士（2級）&lt;/strong&gt;、&lt;strong&gt;塗装技能士（2級）&lt;/strong&gt;、&lt;strong&gt;左官技能士（2級）&lt;/strong&gt; は実務2年で受験可能。技能士保有者は元請から直接指名されるケースが多く、単価交渉力が上がります。&lt;/p&gt;&lt;h2&gt;5. 独立への道&lt;/h2&gt;&lt;p&gt;内装業は &lt;strong&gt;軽トラ1台と道具一式で開業可能&lt;/strong&gt; な低投資業種。東京は元請会社や設計事務所との接点が多く、独立後の仕事獲得がしやすい環境です。建設業許可（内装仕上工事業）は500万円未満の工事なら不要で、開業初年度からハードルが低い職種です。&lt;/p&gt;&lt;h2&gt;6. 体力負担と長期キャリア&lt;/h2&gt;&lt;p&gt;クロス・塗装は &lt;strong&gt;ハシゴ・脚立作業&lt;/strong&gt; が多く膝腰への負担あり。左官・タイルはモルタル運搬で背中・肩を使います。50代以降は元請の管理側に回るか、現場監督・設計補助への転身が一般的なルートです。&lt;/p&gt;&lt;h2&gt;まとめ&lt;/h2&gt;&lt;p&gt;東京の内装・仕上げは &lt;strong&gt;独立しやすく・技能で稼げる&lt;/strong&gt; 古典的な職人スタイルが今も通用する世界。技能士資格と腕で年収700万円超は十分到達可能です。&lt;/p&gt;",
    category: "job-type",
    subcategory: null,
    tags: ["東京", "内装", "クロス", "塗装", "左官", "年収"],
    metaDescription:
      "東京の内装・仕上げ職人（クロス・塗装・左官・タイル）の年収相場、求人タイプ、取りたい技能士資格、独立への道、長期キャリアまでゲンバキャリアが東京の実例ベースでまとめます。",
    publishedAt: new Date("2026-05-25T09:00:00+09:00"),
  },
  {
    slug: "tokyo-demolition-jobs-guide",
    title: "東京の解体・産廃業 求人と年収｜アスベスト規制時代の働き方",
    excerpt:
      "東京の解体工事は再開発と老朽建築更新で増加傾向。アスベスト事前調査の法定化で資格保有者の単価が上昇しています。解体作業員・重機オペ・産廃ドライバーの年収を解説。",
    body: "&lt;p&gt;東京の解体工事業は、&lt;strong&gt;再開発に伴う既存建物の解体&lt;/strong&gt; と、築40〜50年経過した老朽マンション・ビルの建替え需要で、求人が増加傾向にあります。2023年から事前調査の法定化が強化された &lt;strong&gt;アスベスト規制&lt;/strong&gt; の影響で、関連資格の保有者は単価が上昇しています。本記事では東京の解体・産廃業の働き方を整理します。&lt;/p&gt;&lt;h2&gt;1. 東京の解体市場の状況&lt;/h2&gt;&lt;p&gt;東京の解体工事高は &lt;strong&gt;年間3,500億円&lt;/strong&gt; 規模で、全国シェアの約15%。木造戸建ての解体から、超高層ビルの大型解体まで現場の幅が広く、専門会社が多数存在します。&lt;/p&gt;&lt;h2&gt;2. 職種別 年収相場&lt;/h2&gt;&lt;table&gt;&lt;tr&gt;&lt;th&gt;職種&lt;/th&gt;&lt;th&gt;未経験〜3年&lt;/th&gt;&lt;th&gt;5〜10年&lt;/th&gt;&lt;th&gt;職長クラス&lt;/th&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;解体作業員（手バラシ・はつり）&lt;/td&gt;&lt;td&gt;340〜420万円&lt;/td&gt;&lt;td&gt;450〜550万円&lt;/td&gt;&lt;td&gt;600〜750万円&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;解体重機オペレーター&lt;/td&gt;&lt;td&gt;400〜500万円&lt;/td&gt;&lt;td&gt;550〜700万円&lt;/td&gt;&lt;td&gt;750〜950万円&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;アスベスト除去作業員&lt;/td&gt;&lt;td&gt;420〜520万円&lt;/td&gt;&lt;td&gt;600〜780万円&lt;/td&gt;&lt;td&gt;800〜1,000万円&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;産廃ドライバー（4t/10t）&lt;/td&gt;&lt;td&gt;380〜470万円&lt;/td&gt;&lt;td&gt;500〜620万円&lt;/td&gt;&lt;td&gt;650〜800万円&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;h2&gt;3. アスベスト関連資格の重要性&lt;/h2&gt;&lt;p&gt;2023年10月から、解体・改修工事の &lt;strong&gt;事前調査と報告が法定化&lt;/strong&gt; されました。「建築物石綿含有建材調査者」「特定化学物質作業主任者」を持つ作業員は、東京の現場で月3〜6万円の手当が加算されることもあります。&lt;/p&gt;&lt;h2&gt;4. 入社前に取りたい資格&lt;/h2&gt;&lt;ul&gt;&lt;li&gt;&lt;strong&gt;車両系建設機械運転技能講習&lt;/strong&gt;（解体機 必須）&lt;/li&gt;&lt;li&gt;&lt;strong&gt;石綿作業主任者&lt;/strong&gt;（2日間講習・約2万円）&lt;/li&gt;&lt;li&gt;&lt;strong&gt;ガス溶接技能講習&lt;/strong&gt;（鉄骨切断に必須）&lt;/li&gt;&lt;li&gt;&lt;strong&gt;中型・大型自動車免許&lt;/strong&gt;（産廃運搬で重宝）&lt;/li&gt;&lt;/ul&gt;&lt;h2&gt;5. 「3K」イメージと実態&lt;/h2&gt;&lt;p&gt;確かに粉塵・騒音・夏冬の屋外作業が中心の業種ですが、近年は &lt;strong&gt;粉塵抑制・防音シート・ミスト散水&lt;/strong&gt; など作業環境改善が進んでいます。職長クラスは現場管理が主業務になるため、体力負担は下がります。&lt;/p&gt;&lt;h2&gt;6. 産廃ドライバーの働き方&lt;/h2&gt;&lt;p&gt;解体現場から処分場への運搬を担う産廃ドライバーは、&lt;strong&gt;1日3〜5往復で土日休み&lt;/strong&gt; の安定した働き方が可能。長距離運送と違って深夜便がないため、家庭との両立がしやすい職種です。&lt;/p&gt;&lt;h2&gt;まとめ&lt;/h2&gt;&lt;p&gt;東京の解体・産廃業は &lt;strong&gt;規制強化が単価アップに直結&lt;/strong&gt; する珍しい業界。アスベスト関連資格を揃えれば、30代で年収700万円超を狙えます。&lt;/p&gt;",
    category: "job-type",
    subcategory: null,
    tags: ["東京", "解体", "産廃", "アスベスト", "年収"],
    metaDescription:
      "東京の解体・産廃業の求人事情を解説。解体作業員・重機オペ・アスベスト除去・産廃ドライバーの年収相場、必要資格、規制強化による単価上昇までゲンバキャリアが整理します。",
    publishedAt: new Date("2026-05-26T09:00:00+09:00"),
  },
  {
    slug: "tokyo-driver-jobs-guide",
    title: "東京のドライバー・重機オペレーター 求人と年収｜建設業界の運転職",
    excerpt:
      "東京の建設業界ドライバーは、ダンプ・トレーラー・ミキサー車・重機オペそれぞれ需要が高水準。免許別の年収、勤務形態、長距離との違いを実例ベースで解説します。",
    body: "&lt;p&gt;東京の建設業界では、ダンプ運転手・トレーラー運転手・ミキサー車運転手・重機オペレーターなど、&lt;strong&gt;運転を本業とする職種&lt;/strong&gt;の需要が高い水準で推移しています。本記事では、東京で建設業界のドライバーとして働く際の年収・働き方・キャリアパスを解説します。&lt;/p&gt;&lt;h2&gt;1. 東京の建設ドライバー需給&lt;/h2&gt;&lt;p&gt;再開発工事に伴う &lt;strong&gt;土砂・残土運搬&lt;/strong&gt;、生コン納入、鉄骨輸送、重機回送、産廃搬出の5本柱で求人が安定。東京都トラック協会の統計では、建設関連トラックの稼働率は &lt;strong&gt;85%以上&lt;/strong&gt; の高水準が続いています。&lt;/p&gt;&lt;h2&gt;2. 車種・免許別 年収相場&lt;/h2&gt;&lt;table&gt;&lt;tr&gt;&lt;th&gt;車種/職種&lt;/th&gt;&lt;th&gt;必要免許&lt;/th&gt;&lt;th&gt;年収レンジ&lt;/th&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;4tダンプ&lt;/td&gt;&lt;td&gt;中型免許&lt;/td&gt;&lt;td&gt;400〜500万円&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;10tダンプ&lt;/td&gt;&lt;td&gt;大型免許&lt;/td&gt;&lt;td&gt;480〜620万円&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;トレーラー（鉄骨・重機回送）&lt;/td&gt;&lt;td&gt;大型＋けん引&lt;/td&gt;&lt;td&gt;550〜750万円&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;ミキサー車&lt;/td&gt;&lt;td&gt;中型〜大型&lt;/td&gt;&lt;td&gt;420〜550万円&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;重機オペ（ラフター・移動式クレーン）&lt;/td&gt;&lt;td&gt;移動式クレーン運転士&lt;/td&gt;&lt;td&gt;550〜780万円&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;ユニック車（4t＋クレーン）&lt;/td&gt;&lt;td&gt;中型＋小型移動式クレーン&lt;/td&gt;&lt;td&gt;430〜550万円&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;h2&gt;3. 長距離運送との違い&lt;/h2&gt;&lt;p&gt;建設ドライバーは &lt;strong&gt;原則 都内・近郊での日帰り運行&lt;/strong&gt;。長距離トラックと違い、家に毎日帰れるのが最大の魅力です。早朝出発（5〜6時）と引き換えに、夕方には現場が終わるため、子育て世代に人気があります。&lt;/p&gt;&lt;h2&gt;4. 求人が出やすい時期&lt;/h2&gt;&lt;p&gt;3〜5月の年度替わりと、9〜11月の下期開始時に増加。中型・大型免許保有者は &lt;strong&gt;通年で売り手市場&lt;/strong&gt; で、転職希望を出せばすぐに反応があります。&lt;/p&gt;&lt;h2&gt;5. 取りたい免許・資格&lt;/h2&gt;&lt;ul&gt;&lt;li&gt;&lt;strong&gt;大型自動車免許&lt;/strong&gt;（10tダンプ・トレーラー牽引車に必須）&lt;/li&gt;&lt;li&gt;&lt;strong&gt;けん引免許&lt;/strong&gt;（トレーラー・重機回送）&lt;/li&gt;&lt;li&gt;&lt;strong&gt;移動式クレーン運転士&lt;/strong&gt;（ラフター・オールテレーン）&lt;/li&gt;&lt;li&gt;&lt;strong&gt;フォークリフト運転技能講習&lt;/strong&gt;（資材積み下ろし）&lt;/li&gt;&lt;li&gt;&lt;strong&gt;車両系建設機械&lt;/strong&gt;（重機オペで必須）&lt;/li&gt;&lt;/ul&gt;&lt;p&gt;免許取得は会社負担で行ってくれるケースも多く、未経験で入社して大型免許を取らせてもらうルートが一般的です。&lt;/p&gt;&lt;h2&gt;6. 独立・一人親方の選択肢&lt;/h2&gt;&lt;p&gt;ダンプ・ユニック車を購入して &lt;strong&gt;一人親方として独立&lt;/strong&gt; する道もあります。東京は元請からの仕事が安定して出るため、年収700〜900万円を狙えますが、車両ローン・保険料・燃料費の経費負担が大きいので、慎重な収支計算が必要です。&lt;/p&gt;&lt;h2&gt;まとめ&lt;/h2&gt;&lt;p&gt;東京の建設ドライバーは &lt;strong&gt;家に帰れる・免許で稼げる・需要安定&lt;/strong&gt; の3拍子が揃った職種。免許取得を会社負担でサポートしてもらえる入口の広さも魅力です。&lt;/p&gt;",
    category: "job-type",
    subcategory: null,
    tags: ["東京", "ドライバー", "重機オペレーター", "ダンプ", "年収"],
    metaDescription:
      "東京の建設業界ドライバー・重機オペレーターの求人を車種別年収、必要免許、長距離との違い、独立可能性まで解説。中型・大型免許で稼ぐ働き方をゲンバキャリアが東京の実例で整理します。",
    publishedAt: new Date("2026-05-27T09:00:00+09:00"),
  },
  {
    slug: "tokyo-survey-jobs-guide",
    title: "東京の測量・設計求人と年収｜BIM 時代の働き方",
    excerpt:
      "東京の測量・設計職は再開発の事前測量、3D 計測、BIM 化で需要拡大中。測量士・CAD オペ・設計補助それぞれの東京での年収と必要スキルを実例ベースで解説します。",
    body: "&lt;p&gt;東京の測量・設計職は、&lt;strong&gt;再開発の事前測量&lt;/strong&gt;、3Dレーザースキャナによる現況計測、BIM（Building Information Modeling）導入の3つの追い風で、需要が拡大しています。本記事では東京で測量・設計職として働く際の年収と必要スキルを解説します。&lt;/p&gt;&lt;h2&gt;1. 東京の測量・設計市場&lt;/h2&gt;&lt;p&gt;東京都内の測量業務市場は &lt;strong&gt;年間1,200億円&lt;/strong&gt; 規模。公共測量（都・国土地理院・国交省）、民間測量（不動産・再開発）、設計事務所兼業の測量と幅広く、若手の採用枠も多くあります。&lt;/p&gt;&lt;h2&gt;2. 職種別 年収相場&lt;/h2&gt;&lt;table&gt;&lt;tr&gt;&lt;th&gt;職種&lt;/th&gt;&lt;th&gt;未経験〜3年&lt;/th&gt;&lt;th&gt;5〜10年&lt;/th&gt;&lt;th&gt;15年以上&lt;/th&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;測量補助&lt;/td&gt;&lt;td&gt;320〜400万円&lt;/td&gt;&lt;td&gt;420〜520万円&lt;/td&gt;&lt;td&gt;550〜650万円&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;測量士（国家資格）&lt;/td&gt;&lt;td&gt;380〜470万円&lt;/td&gt;&lt;td&gt;520〜680万円&lt;/td&gt;&lt;td&gt;750〜950万円&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;CAD オペレーター&lt;/td&gt;&lt;td&gt;330〜420万円&lt;/td&gt;&lt;td&gt;450〜570万円&lt;/td&gt;&lt;td&gt;600〜750万円&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;構造設計補助&lt;/td&gt;&lt;td&gt;380〜480万円&lt;/td&gt;&lt;td&gt;520〜700万円&lt;/td&gt;&lt;td&gt;800〜1,100万円&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;h2&gt;3. 取りたい資格・スキル&lt;/h2&gt;&lt;ul&gt;&lt;li&gt;&lt;strong&gt;測量士補&lt;/strong&gt;（学科のみで取得可、文系出身者の入口）&lt;/li&gt;&lt;li&gt;&lt;strong&gt;測量士&lt;/strong&gt;（実務経験＋試験 or 国土地理院認定校卒業）&lt;/li&gt;&lt;li&gt;&lt;strong&gt;AutoCAD / Civil 3D / Revit&lt;/strong&gt; の操作スキル&lt;/li&gt;&lt;li&gt;&lt;strong&gt;3Dレーザースキャナ&lt;/strong&gt; 操作経験&lt;/li&gt;&lt;li&gt;&lt;strong&gt;UAV（ドローン）測量&lt;/strong&gt; 講習（10万円前後）&lt;/li&gt;&lt;/ul&gt;&lt;h2&gt;4. BIM 化の流れ&lt;/h2&gt;&lt;p&gt;国交省が2023年から &lt;strong&gt;公共建築のBIM原則導入&lt;/strong&gt; を打ち出し、東京の大手設計事務所・ゼネコンは急速にBIM化を進めています。Revit / ArchiCAD 操作スキルを持つ若手は &lt;strong&gt;月給+3〜5万円&lt;/strong&gt; のスキル手当が付くケースも増えています。&lt;/p&gt;&lt;h2&gt;5. 働き方の特徴&lt;/h2&gt;&lt;p&gt;測量は &lt;strong&gt;現場（外業）と事務所（内業）の半々&lt;/strong&gt;。雨天時や夜間（道路測量）の業務もあるものの、土木職人ほど体力負担はありません。設計補助は完全な内勤で、女性比率も増えています。&lt;/p&gt;&lt;h2&gt;6. 長期キャリア&lt;/h2&gt;&lt;p&gt;測量士は独立して &lt;strong&gt;測量事務所開業&lt;/strong&gt; が可能。東京は不動産取引に伴う境界確定測量の需要が安定しており、独立で年収1,000万円超も狙えます。&lt;/p&gt;&lt;h2&gt;まとめ&lt;/h2&gt;&lt;p&gt;東京の測量・設計は &lt;strong&gt;頭脳労働＋現場経験＋IT スキル&lt;/strong&gt; のバランスで稼げる分野。BIM とドローン測量を学んでおけば10年先も食いっぱぐれない職種です。&lt;/p&gt;",
    category: "job-type",
    subcategory: null,
    tags: ["東京", "測量", "CAD", "設計", "BIM", "年収"],
    metaDescription:
      "東京の測量・設計求人を職種別年収、測量士・CAD・BIM 資格、3D 計測やドローン測量など新技術への対応、独立への道までゲンバキャリアが東京の実例ベースでまとめます。",
    publishedAt: new Date("2026-05-28T09:00:00+09:00"),
  },
  {
    slug: "tokyo-construction-overview",
    title: "東京の建設業界全体動向｜再開発・インフラ更新・人手不足の今",
    excerpt:
      "東京の建設業界は再開発ラッシュ、老朽インフラ更新、慢性的人手不足で激変期。市場規模、9 職種の需要バランス、若手の参入余地、向こう 10 年の展望を俯瞰します。",
    body: "&lt;p&gt;東京の建設業界は、丸の内・大手町・八重洲・池袋・渋谷・新宿などの &lt;strong&gt;同時多発再開発&lt;/strong&gt;、首都高・上下水道などの &lt;strong&gt;老朽インフラ更新&lt;/strong&gt;、そして全業種で深刻化する &lt;strong&gt;人手不足&lt;/strong&gt; という3つの大きな潮流が同時進行しています。本記事では東京の建設業界全体を俯瞰し、職種別の需要と今後10年の展望を整理します。&lt;/p&gt;&lt;h2&gt;1. 東京の建設投資額&lt;/h2&gt;&lt;p&gt;2024年度の東京都内の建設投資額は &lt;strong&gt;約11兆円&lt;/strong&gt;。これは全国の建設投資額（約65兆円）の17%に相当します。内訳は民間建築60%、公共土木25%、民間土木10%、その他5%で、新築と改修の比率はほぼ50:50となっています。&lt;/p&gt;&lt;h2&gt;2. 主要再開発プロジェクト&lt;/h2&gt;&lt;ul&gt;&lt;li&gt;&lt;strong&gt;東京駅周辺&lt;/strong&gt;: 八重洲地区再開発（〜2028年）、TOKYO TORCH（〜2027年）&lt;/li&gt;&lt;li&gt;&lt;strong&gt;品川・港南&lt;/strong&gt;: TAKANAWA GATEWAY CITY、品川駅西口再開発&lt;/li&gt;&lt;li&gt;&lt;strong&gt;渋谷&lt;/strong&gt;: 渋谷駅桜丘口、渋谷二丁目西地区&lt;/li&gt;&lt;li&gt;&lt;strong&gt;池袋&lt;/strong&gt;: 池袋駅西口、東池袋一丁目地区&lt;/li&gt;&lt;li&gt;&lt;strong&gt;新宿&lt;/strong&gt;: 新宿駅西口再開発、歌舞伎町タワー周辺&lt;/li&gt;&lt;/ul&gt;&lt;p&gt;これらは10年単位の超大型案件で、施工管理・躯体職人・設備工事士の需要を支える基盤になっています。&lt;/p&gt;&lt;h2&gt;3. 9 職種別の需給バランス&lt;/h2&gt;&lt;table&gt;&lt;tr&gt;&lt;th&gt;職種&lt;/th&gt;&lt;th&gt;需要&lt;/th&gt;&lt;th&gt;供給&lt;/th&gt;&lt;th&gt;入りやすさ&lt;/th&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;施工管理&lt;/td&gt;&lt;td&gt;★★★★★&lt;/td&gt;&lt;td&gt;★★&lt;/td&gt;&lt;td&gt;非常に入りやすい&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;建築・躯体&lt;/td&gt;&lt;td&gt;★★★★★&lt;/td&gt;&lt;td&gt;★★&lt;/td&gt;&lt;td&gt;非常に入りやすい&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;土木&lt;/td&gt;&lt;td&gt;★★★★&lt;/td&gt;&lt;td&gt;★★★&lt;/td&gt;&lt;td&gt;入りやすい&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;電気・設備&lt;/td&gt;&lt;td&gt;★★★★★&lt;/td&gt;&lt;td&gt;★★&lt;/td&gt;&lt;td&gt;非常に入りやすい&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;内装・仕上げ&lt;/td&gt;&lt;td&gt;★★★★&lt;/td&gt;&lt;td&gt;★★★&lt;/td&gt;&lt;td&gt;入りやすい&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;解体・産廃&lt;/td&gt;&lt;td&gt;★★★★&lt;/td&gt;&lt;td&gt;★★&lt;/td&gt;&lt;td&gt;入りやすい&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;ドライバー・重機&lt;/td&gt;&lt;td&gt;★★★★&lt;/td&gt;&lt;td&gt;★★&lt;/td&gt;&lt;td&gt;免許次第で即戦力&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;測量・設計&lt;/td&gt;&lt;td&gt;★★★&lt;/td&gt;&lt;td&gt;★★★&lt;/td&gt;&lt;td&gt;資格保有者は売り手市場&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;h2&gt;4. 人手不足の構造&lt;/h2&gt;&lt;p&gt;東京の建設業就業者は &lt;strong&gt;約65万人&lt;/strong&gt; ですが、55歳以上が35%を占め、29歳以下は11%程度。10年後には20万人以上が引退見込みで、若手・中途の採用は &lt;strong&gt;構造的な売り手市場&lt;/strong&gt; が継続します。&lt;/p&gt;&lt;h2&gt;5. 賃金水準と働き方改革&lt;/h2&gt;&lt;p&gt;東京は地方より &lt;strong&gt;年収100〜200万円高い&lt;/strong&gt; のが標準。2024年4月の建設業働き方改革（残業月45時間規制）以降、大手・準大手は週休2日制が定着しつつあり、若手の流入が増えています。&lt;/p&gt;&lt;h2&gt;6. 向こう10年の展望&lt;/h2&gt;&lt;p&gt;2030年に向けて、東京は &lt;strong&gt;リニア中央新幹線開業&lt;/strong&gt;、&lt;strong&gt;首都高築地川地下化&lt;/strong&gt;、&lt;strong&gt;羽田空港アクセス強化&lt;/strong&gt; など大型インフラ案件が続きます。建設業界全体で見れば、東京は今後10年も最も仕事の絶えないエリアであり続けるでしょう。&lt;/p&gt;&lt;h2&gt;まとめ&lt;/h2&gt;&lt;p&gt;東京の建設業界は &lt;strong&gt;再開発・インフラ更新・人手不足&lt;/strong&gt; の三重追い風で、未経験から飛び込んでも長く稼げる環境です。職種選びは需給バランスを見て、自分の適性とすり合わせるのが成功への近道です。&lt;/p&gt;",
    category: "industry",
    subcategory: null,
    tags: ["東京", "建設業界", "再開発", "人手不足", "市場動向"],
    metaDescription:
      "東京の建設業界全体動向を俯瞰。再開発プロジェクト、9 職種の需給バランス、人手不足の構造、賃金水準、向こう 10 年の展望までゲンバキャリアが市場データベースでまとめます。",
    publishedAt: new Date("2026-05-29T09:00:00+09:00"),
  },
  {
    slug: "tokyo-no-experience-construction",
    title: "東京で未経験から建設業に飛び込む｜20代・30代のはじめ方",
    excerpt:
      "東京は未経験者にとって全国で最も建設業に入りやすいエリア。求人数の豊富さ、研修制度、寮付き会社、最初の 3 ヶ月で押さえるべきポイントを実例で解説します。",
    body: "&lt;p&gt;「東京で未経験から建設業に挑戦したい」という相談はゲンバキャリアでも非常に多いテーマです。結論から言えば &lt;strong&gt;東京は全国で最も未経験者の入口が広いエリア&lt;/strong&gt;。本記事では、未経験から東京で建設業に飛び込む際の現実的な進め方を解説します。&lt;/p&gt;&lt;h2&gt;1. なぜ東京が未経験者向きなのか&lt;/h2&gt;&lt;ul&gt;&lt;li&gt;求人数が圧倒的に多く、選択肢が広い&lt;/li&gt;&lt;li&gt;研修制度や資格取得支援が手厚い大手・準大手が多い&lt;/li&gt;&lt;li&gt;寮・社宅完備の会社が多く、地方出身者も住居を確保しやすい&lt;/li&gt;&lt;li&gt;同期入社の同年代が多く、孤立しにくい&lt;/li&gt;&lt;/ul&gt;&lt;h2&gt;2. 未経験スタートのおすすめ職種&lt;/h2&gt;&lt;table&gt;&lt;tr&gt;&lt;th&gt;職種&lt;/th&gt;&lt;th&gt;特徴&lt;/th&gt;&lt;th&gt;1 年目年収&lt;/th&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;施工管理（派遣会社）&lt;/td&gt;&lt;td&gt;研修充実、書類仕事中心&lt;/td&gt;&lt;td&gt;380〜450万円&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;電気工事（中堅サブコン）&lt;/td&gt;&lt;td&gt;免許取得サポート手厚い&lt;/td&gt;&lt;td&gt;360〜440万円&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;鉄筋・型枠（中堅専門工事）&lt;/td&gt;&lt;td&gt;手に職、職長まで明確&lt;/td&gt;&lt;td&gt;340〜430万円&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;ドライバー（中型免許）&lt;/td&gt;&lt;td&gt;運転好きに最適、日帰り&lt;/td&gt;&lt;td&gt;380〜460万円&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;h2&gt;3. 入社前に取れる資格（3〜5万円・1週間以内）&lt;/h2&gt;&lt;ul&gt;&lt;li&gt;&lt;strong&gt;玉掛け技能講習&lt;/strong&gt;（3日間）&lt;/li&gt;&lt;li&gt;&lt;strong&gt;フォークリフト運転技能講習&lt;/strong&gt;（4〜5日間）&lt;/li&gt;&lt;li&gt;&lt;strong&gt;小型移動式クレーン運転技能講習&lt;/strong&gt;（3日間）&lt;/li&gt;&lt;li&gt;&lt;strong&gt;足場の組立等作業従事者特別教育&lt;/strong&gt;（半日）&lt;/li&gt;&lt;/ul&gt;&lt;p&gt;ハローワークの教育訓練給付対象になる講座も多く、費用は実質ゼロで取れる場合もあります。&lt;/p&gt;&lt;h2&gt;4. 寮・社宅完備の会社の選び方&lt;/h2&gt;&lt;p&gt;東京は家賃が高いため、&lt;strong&gt;社員寮や借上げ社宅制度&lt;/strong&gt; を持つ会社を選ぶと月3〜5万円の家賃補助が事実上得られます。応募時に「寮の有無」「家賃補助」「敷礼負担」を必ず確認しましょう。&lt;/p&gt;&lt;h2&gt;5. 最初の 3 ヶ月で押さえるべきこと&lt;/h2&gt;&lt;ul&gt;&lt;li&gt;朝礼・KY ミーティング（危険予知）の参加マナー&lt;/li&gt;&lt;li&gt;ヘルメット・安全帯・安全靴の正しい使い方&lt;/li&gt;&lt;li&gt;先輩職人への質問の仕方（タイミングと言葉遣い）&lt;/li&gt;&lt;li&gt;現場で使う道具の名前を覚える&lt;/li&gt;&lt;li&gt;体調管理（睡眠 7 時間、水分補給、塩分タブレット）&lt;/li&gt;&lt;/ul&gt;&lt;h2&gt;6. よくある質問&lt;/h2&gt;&lt;p&gt;&lt;strong&gt;Q. 体力に自信がない…&lt;/strong&gt; A. 施工管理・測量・CAD なら現場作業は補助程度。&lt;br&gt;&lt;strong&gt;Q. 高卒・中卒でも入れる？&lt;/strong&gt; A. 建設業は学歴よりも継続性・素直さを重視。十分に入れる。&lt;br&gt;&lt;strong&gt;Q. 1 ヶ月で辞めたくなったら？&lt;/strong&gt; A. まず先輩に相談。配置換え・職種変更で解決するケースも多い。&lt;/p&gt;&lt;h2&gt;まとめ&lt;/h2&gt;&lt;p&gt;東京は &lt;strong&gt;未経験から建設業に飛び込むのに日本一適したエリア&lt;/strong&gt;。求人の豊富さ、研修制度、住居サポートを活用すれば、半年で一人前への土台を固められます。&lt;/p&gt;",
    category: "career",
    subcategory: null,
    tags: ["東京", "未経験歓迎", "20代", "30代", "建設業"],
    metaDescription:
      "東京で未経験から建設業に挑戦する際のはじめ方を解説。職種選び、入社前資格、寮付き会社の選び方、最初の 3 ヶ月で押さえるポイントまでゲンバキャリアが実例ベースでまとめます。",
    publishedAt: new Date("2026-05-30T09:00:00+09:00"),
  },
]
